/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TimeTrackerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE = "time-tracker-view";
var DAILY_GOAL = 7.5;
function parseHours(s) {
  const m = s.match(/^(\d+(?:\.\d+)?)\s*h?$/i);
  return m ? parseFloat(m[1]) : 0;
}
function dateKey(ts) {
  const d = new Date(ts);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}
function isToday(ts) {
  return dateKey(ts) === dateKey(Date.now());
}
var DAY_NAMES = ["\u0412\u0441", "\u041F\u043D", "\u0412\u0442", "\u0421\u0440", "\u0427\u0442", "\u041F\u0442", "\u0421\u0431"];
var MONTH_NAMES = ["\u044F\u043D\u0432", "\u0444\u0435\u0432", "\u043C\u0430\u0440", "\u0430\u043F\u0440", "\u043C\u0430\u0439", "\u0438\u044E\u043D", "\u0438\u044E\u043B", "\u0430\u0432\u0433", "\u0441\u0435\u043D", "\u043E\u043A\u0442", "\u043D\u043E\u044F", "\u0434\u0435\u043A"];
function formatDate(ts) {
  const d = new Date(ts);
  const dayName = DAY_NAMES[d.getDay()];
  const monthName = MONTH_NAMES[d.getMonth()];
  return `${dayName}, ${d.getDate()} ${monthName} ${d.getFullYear()}`;
}
var TimeTrackerPlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.registerView(VIEW_TYPE, (leaf) => new TimeTrackerView(leaf, this));
    this.addRibbonIcon("clock", "Time Tracker", () => this.activateView());
    this.addCommand({
      id: "open-time-tracker",
      name: "Open Time Tracker",
      callback: () => this.activateView()
    });
  }
  async activateView() {
    const { workspace } = this.app;
    workspace.detachLeavesOfType(VIEW_TYPE);
    const leaf = workspace.getLeaf(true);
    await leaf.setViewState({ type: VIEW_TYPE, active: true });
    workspace.revealLeaf(leaf);
  }
};
var TimeTrackerView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.entries = [];
    this.initialRender = true;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return "Time Tracker";
  }
  getIcon() {
    return "clock";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("tt-container");
    this.renderForm(container);
    this.listEl = container.createDiv({ cls: "tt-list" });
    await this.renderList();
  }
  renderForm(container) {
    const form = container.createDiv({ cls: "tt-form" });
    this.textInput = form.createEl("input", {
      type: "text",
      placeholder: "\u0427\u0442\u043E \u0434\u0435\u043B\u0430\u043B?",
      cls: "tt-input"
    });
    this.textInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter")
        this.timeInput.focus();
    });
    this.timeInput = form.createEl("input", {
      type: "text",
      placeholder: "\u0412\u0440\u0435\u043C\u044F: 0.0",
      cls: "tt-input tt-input-narrow"
    });
    this.timeInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter")
        this.addEntry();
    });
    this.dateInput = form.createEl("input", {
      type: "date",
      cls: "tt-input tt-input-date"
    });
    this.dateInput.value = dateKey(Date.now());
    this.dateInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter")
        this.addEntry();
    });
    const label = form.createEl("label", { cls: "tt-checkbox-label" });
    this.checkedInput = label.createEl("input", { type: "checkbox" });
    label.createSpan({ text: " \u0412\u043D\u0435\u0441\u0435\u043D\u043E" });
    const btn = form.createEl("button", { text: "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C", cls: "tt-btn" });
    btn.addEventListener("click", () => this.addEntry());
  }
  async addEntry() {
    const text = this.textInput.value.trim();
    const time = this.timeInput.value.trim();
    if (!text || !time) {
      new import_obsidian.Notice("\u0417\u0430\u043F\u043E\u043B\u043D\u0438\u0442\u0435 \u043E\u0431\u0430 \u043F\u043E\u043B\u044F");
      return;
    }
    if (!/^\d+(?:\.\d+)?$/.test(time)) {
      new import_obsidian.Notice("\u041D\u0435\u0432\u0435\u0440\u043D\u044B\u0439 \u0444\u043E\u0440\u043C\u0430\u0442 \u0432\u0440\u0435\u043C\u0435\u043D\u0438. \u0418\u0441\u043F\u043E\u043B\u044C\u0437\u0443\u0439\u0442\u0435: 1, 1.5, 2.5");
      return;
    }
    const dateStr = this.dateInput.value || dateKey(Date.now());
    const timestamp = (/* @__PURE__ */ new Date(dateStr + "T12:00:00")).getTime();
    const entry = {
      id: crypto.randomUUID(),
      text,
      time: time.toLowerCase(),
      checked: this.checkedInput.checked,
      timestamp
    };
    this.entries.push(entry);
    await this.save();
    await this.renderList();
    this.textInput.value = "";
    this.timeInput.value = "";
    this.dateInput.value = dateKey(Date.now());
    this.checkedInput.checked = false;
    this.textInput.focus();
  }
  async save() {
    await this.plugin.saveData({ entries: this.entries });
  }
  async deleteEntry(id) {
    this.entries = this.entries.filter((e) => e.id !== id);
    await this.save();
    await this.renderList();
  }
  async toggleEntry(id) {
    const entry = this.entries.find((e) => e.id === id);
    if (entry) {
      entry.checked = !entry.checked;
      await this.save();
      await this.renderList();
    }
  }
  async updateEntry(id, field, value) {
    const entry = this.entries.find((e) => e.id === id);
    if (entry) {
      entry[field] = value;
      await this.save();
    }
    await this.renderList();
  }
  async renderList() {
    const data = await this.plugin.loadData();
    this.entries = (data == null ? void 0 : data.entries) || [];
    const openDates = /* @__PURE__ */ new Set();
    if (!this.initialRender) {
      this.listEl.querySelectorAll("details.tt-day").forEach((el) => {
        const details = el;
        if (details.open) {
          const date = details.getAttr("data-date");
          if (date)
            openDates.add(date);
        }
      });
      const todayDate = dateKey(Date.now());
      if (!this.listEl.querySelector(`details.tt-day[data-date="${todayDate}"]`)) {
        openDates.add(todayDate);
      }
    }
    this.listEl.empty();
    const groups = /* @__PURE__ */ new Map();
    for (const entry of this.entries) {
      const key = dateKey(entry.timestamp);
      if (!groups.has(key))
        groups.set(key, []);
      groups.get(key).push(entry);
    }
    const sortedDates = Array.from(groups.keys()).sort().reverse();
    for (const dateStr of sortedDates) {
      const dayEntries = groups.get(dateStr);
      const totalHours = dayEntries.reduce(
        (sum, e) => sum + parseHours(e.time),
        0
      );
      const allChecked = dayEntries.every((e) => e.checked);
      const today = isToday(new Date(dateStr).getTime());
      const details = this.listEl.createEl("details", { cls: "tt-day" });
      details.setAttr("data-date", dateStr);
      if (this.initialRender ? today : openDates.has(dateStr)) {
        details.setAttr("open", "");
      }
      const headerText = `${formatDate(new Date(dateStr).getTime())} \u2014 ${totalHours.toFixed(1)}h`;
      const summary = details.createEl("summary", { cls: "tt-day-summary" });
      if (!today) {
        if (totalHours < DAILY_GOAL) {
          summary.addClass("tt-red");
        } else if (allChecked) {
          summary.addClass("tt-green");
        } else {
          summary.addClass("tt-orange");
        }
      }
      summary.textContent = headerText;
      const sortedEntries = dayEntries.sort(
        (a, b) => b.timestamp - a.timestamp
      );
      for (const entry of sortedEntries) {
        const row = details.createDiv({ cls: "tt-entry" });
        row.dataset.id = entry.id;
        const cb = row.createEl("input", {
          type: "checkbox",
          cls: "tt-entry-cb"
        });
        cb.checked = entry.checked;
        cb.addEventListener("change", () => this.toggleEntry(entry.id));
        const textSpan = row.createSpan({
          cls: "tt-entry-text",
          text: entry.text
        });
        textSpan.addEventListener(
          "click",
          () => this.makeEditable(textSpan, entry, "text")
        );
        const timeSpan = row.createSpan({
          cls: "tt-entry-time",
          text: entry.time.endsWith("h") ? entry.time : entry.time + "h"
        });
        timeSpan.addEventListener(
          "click",
          () => this.makeEditable(timeSpan, entry, "time")
        );
        const delBtn = row.createEl("button", { cls: "tt-del-btn", text: "\u2715" });
        delBtn.addEventListener("click", () => this.deleteEntry(entry.id));
      }
    }
    this.initialRender = false;
  }
  makeEditable(span, entry, field) {
    const input = document.createElement("input");
    input.type = "text";
    input.value = entry[field];
    input.className = "tt-edit-input";
    const finish = async () => {
      let val = input.value.trim();
      if (field === "time")
        val = val.replace(/\s*h$/i, "");
      if (val) {
        if (field === "time" && !/^\d+(?:\.\d+)?$/.test(val)) {
          new import_obsidian.Notice("\u041D\u0435\u0432\u0435\u0440\u043D\u044B\u0439 \u0444\u043E\u0440\u043C\u0430\u0442 \u0432\u0440\u0435\u043C\u0435\u043D\u0438. \u0418\u0441\u043F\u043E\u043B\u044C\u0437\u0443\u0439\u0442\u0435: 1, 1.5, 2.5");
          await this.renderList();
          return;
        }
        if (val !== entry[field]) {
          await this.updateEntry(entry.id, field, val);
        } else {
          await this.renderList();
        }
      } else {
        await this.renderList();
      }
    };
    input.addEventListener("blur", finish);
    input.addEventListener("keydown", async (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        input.blur();
      }
      if (e.key === "Escape") {
        e.preventDefault();
        await this.renderList();
      }
    });
    span.replaceWith(input);
    input.focus();
    input.select();
  }
};
